name: Semgrep Analysis

on: 
  push:
    branches:
      - test
permissions:
  contents: write  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Semgrep
      - name: Set up Semgrep
        run: docker pull semgrep/semgrep

      - name: Run Semgrep
        run: docker run --rm -v $(pwd):/src semgrep/semgrep semgrep scan --config="p/default" --json --output semgrep.json --metrics=off
       
      - name: Install prospector-html
        run: python -m pip install prospector2html

      - name: Convert Semgrep results to HTML
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep || true

      # Publish to GitHub Pages
      - name: Move reports to public folder
        run: |
          mkdir -p semgrep
          mv semgrep-report.html semgrep
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SEMGREP_TOKEN }}
          publish_dir: semgrep