name: Snyk Analysis
env:
  DOTNET_VERSION: '8.x'  # la versión de .NET

on: 
  push:
    branches: ["main"]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Snyk CLI
        uses: snyk/actions/setup@master

      - name: Configurando la versión de .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}  

      - name: Instalar Snyk-to-HTML
        run: npm install -g snyk-to-html

      - name: Snyk Code test
        run: snyk code test --sarif-file-output=snyk.sarif --json-file-output=snyk-report.json || echo "Snyk code test completed with issues"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Verificar existencia del archivo SARIF
        run: ls -la snyk.sarif

      - name: Mover archivo SARIF a Reportes
        run: |
          mkdir -p ../Reportes  # Crea el directorio si no existe
          mv snyk.sarif ../Reportes/  # Mueve el archivo SARIF a la carpeta Reportes

      - name: Generar reporte HTML desde SARIF
        run: snyk-to-html -i ../Reportes/snyk.sarif -o ../Reportes/snyk-report.html  # Genera el reporte en la carpeta Reportes

      - name: Verificar existencia del reporte HTML
        run: ls -la ../Reportes/snyk-report.html

      - name: Configurar Git para publicar en GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - id: deploy-pages
        name: Publicar reporte en GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          cp ../Reportes/snyk-report.html index.html  # Copia el archivo HTML generado
          git add index.html
          git commit -m "Publicando reporte de Snyk"
          git push --force --set-upstream origin gh-pages
