name: Snyk Security

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Verificar existencia de ProyectoFinal
        run: ls -la ProyectoFinal || echo "Carpeta ProyectoFinal no existe"

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Authenticate with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Instalar Snyk-to-HTML
        run: npm install -g snyk-to-html

      - name: Snyk Code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: ProyectoFinal
        run: snyk code test --sarif --all-projects > snyk-code.sarif || echo "Snyk code test failed with exit code $?"

      - name: Generar reporte HTML desde SARIF
        working-directory: ProyectoFinal
        run: snyk-to-html -i snyk-code.sarif -o snyk-report.html

      - name: Verificar existencia del reporte HTML
        working-directory: ProyectoFinal
        run: ls -la snyk-report.html

      - name: Configurar Git para publicar en GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"    

      - name: Publicar reporte en GitHub Pages
        working-directory: ProyectoFinal        
        env:
            GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  
        run: |
            git checkout --orphan gh-pages
            git reset --hard
            cp snyk-report.html reportesnyk.html  # Copia el archivo generado
            git add reportesnyk.html
            git commit -m "Publicando reporte de Snyk"
            git push --force --set-upstream https://x-access-token:${GITHUB_TOKEN}@github.com/UPT-FAING-EPIS/proyecto-si784-2024-ii-u1-chambi_floresq_leyva.git gh-pages
      
      - name: Snyk Open Source monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: ProyectoFinal
        run: snyk monitor

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ProyectoFinal/snyk-code.sarif

      - name: Verificar existencia del archivo de log
        run: ls -la workflow-errors.log || echo "Archivo de log no generado"
